### ISSUE TITLE
NPE in AssociationList.getCurrentName from CivChat2 AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#104]
2015-05-17 12:40:49 [ERROR] Could not pass event AsyncPlayerChatEvent to CivChat2 v1.0.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.chat(PlayerConnection.java:1061) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:999) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.namelayer.database.AssociationList.getCurrentName(AssociationList.java:118) ~[?:?]
        at vg.civcraft.mc.namelayer.NameAPI.getCurrentName(NameAPI.java:32) ~[?:?]
        at vg.civcraft.mc.civchat2.CivChat2Manager.broadcastMessage(CivChat2Manager.java:248) ~[?:?]
        at vg.civcraft.mc.civchat2.listeners.CivChat2Listener.PlayerChatEvent(CivChat2Listener.java:102) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 11 more

**Comment by erocs** [comment]
Might be related.

2015-05-17 12:40:49 [WARN] java.sql.SQLException: Operation not allowed after ResultSet closed
2015-05-17 12:40:49 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
2015-05-17 12:40:49 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
2015-05-17 12:40:49 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
2015-05-17 12:40:49 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
2015-05-17 12:40:49 [WARN]      at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
2015-05-17 12:40:49 [WARN]      at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:838)
2015-05-17 12:40:49 [WARN]      at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5656)
2015-05-17 12:40:49 [WARN]      at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5576)
2015-05-17 12:40:49 [WARN]      at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5616)
2015-05-17 12:40:49 [WARN]      at vg.civcraft.mc.namelayer.database.AssociationList.getUUID(AssociationList.java:105)
2015-05-17 12:40:49 [WARN]      at vg.civcraft.mc.namelayer.NameAPI.getUUID(NameAPI.java:24)
2015-05-17 12:40:49 [WARN]      at vg.civcraft.mc.civchat2.CivChat2Manager.broadcastMessage(CivChat2Manager.java:222)
2015-05-17 12:40:49 [WARN]      at vg.civcraft.mc.civchat2.listeners.CivChat2Listener.PlayerChatEvent(CivChat2Listener.java:102)
2015-05-17 12:40:49 [WARN]      at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source)
2015-05-17 12:40:49 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-05-17 12:40:49 [WARN]      at java.lang.reflect.Method.invoke(Method.java:497)
2015-05-17 12:40:49 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
2015-05-17 12:40:49 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2015-05-17 12:40:49 [WARN]      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
2015-05-17 12:40:49 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
2015-05-17 12:40:49 [WARN]      at net.minecraft.server.v1_8_R2.PlayerConnection.chat(PlayerConnection.java:1061)
2015-05-17 12:40:49 [WARN]      at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:999)
2015-05-17 12:40:49 [WARN]      at net.minecraft.server.v1_8_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
2015-05-17 12:40:49 [WARN]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2015-05-17 12:40:49 [WARN]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2015-05-17 12:40:49 [WARN]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-05-17 12:40:49 [WARN]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-05-17 12:40:49 [WARN]      at java.lang.Thread.run(Thread.java:745)

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/commit/c357be874b2b765dc6e67394ce5133208df410dd
