### ISSUE TITLE
NPE in NameAPI.getUUID from async-MiscLog task

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#105]
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.ResultSetImpl.buildIndexMapping(ResultSetImpl.java:758)
        at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1108)
        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5616)
        at vg.civcraft.mc.namelayer.database.AssociationList.getUUID(AssociationList.java:105)
        at vg.civcraft.mc.namelayer.NameAPI.getUUID(NameAPI.java:24)

**Comment by rourke750** [comment]
I'll fix this later today

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/commit/c357be874b2b765dc6e67394ce5133208df410dd
