### ISSUE TITLE
NPE in AssociationList.getCurrentName from CivChat2FileLogger.writeToChatLog

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#106]
[INFO] [CivChat2] [Debug] playerKickEvent occured
[INFO] ABC lost connection: §cYou §6were §ekicked §adue §9to in§5activity
[INFO] [MiscLog] ABC logged out at
[INFO] [CivChat2] [Debug] PlayerChatEvent occured
[INFO] [CivChat2] [Debug] getChannel returning null
[INFO] [CivChat2] [Debug] PlayerChatEvent calling chatman.broadcastMessage()
[INFO] [CivChat2] [Debug] playerQuitEvent occured
[ERROR] Could not pass event AsyncPlayerChatEvent to CivChat2 v1.0.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.chat(PlayerConnection.java:1061) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:999) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.ResultSetImpl.buildIndexMapping(ResultSetImpl.java:754) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1108) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5616) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at vg.civcraft.mc.namelayer.database.AssociationList.getCurrentName(AssociationList.java:121) ~[?:?]
        at vg.civcraft.mc.namelayer.NameAPI.getCurrentName(NameAPI.java:32) ~[?:?]
        at vg.civcraft.mc.civchat2.zipper.CivChat2FileLogger.writeToChatLog(CivChat2FileLogger.java:158) ~[?:?]
        at vg.civcraft.mc.civchat2.CivChat2Manager.broadcastMessage(CivChat2Manager.java:215) ~[?:?]
        at vg.civcraft.mc.civchat2.listeners.CivChat2Listener.PlayerChatEvent(CivChat2Listener.java:102) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 11 more
[WARN] handleDisconnection() called twice

**Comment by rourke750** [comment]
I think its from CivChat initiating before the NameApi class is properly
initiated.

**Comment by jjj5311** [comment]
This should be fixed with the latest civchat
