### ISSUE TITLE
nlmg MySQLIntegrityConstraintViolationException

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#108]
2015-05-28 12:18:37 [INFO] ABC issued server command: /nlmg G1 G2
2015-05-28 12:18:37 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'UUID_BCD' for key 'uq_meber_faction'
2015-05-28 12:18:37 [WARN]      at sun.reflect.GeneratedConstructorAccessor191.newInstance(Unknown Source)
2015-05-28 12:18:37 [WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2015-05-28 12:18:37 [WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
2015-05-28 12:18:37 [WARN]      at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2015-05-28 12:18:37 [WARN]      at com.mysql.jdbc.Util.getInstance(Util.java:382)
2015-05-28 12:18:37 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
2015-05-28 12:18:37 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
2015-05-28 12:18:37 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2015-05-28 12:18:37 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2015-05-28 12:18:37 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2015-05-28 12:18:37 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2015-05-28 12:18:37 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2015-05-28 12:18:37 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
2015-05-28 12:18:37 [WARN]      at vg.civcraft.mc.namelayer.database.GroupManagerDao.addMember(GroupManagerDao.java:488)
2015-05-28 12:18:37 [WARN]      at vg.civcraft.mc.namelayer.group.groups.PrivateGroup.addMember(PrivateGroup.java:31)
2015-05-28 12:18:37 [WARN]      at vg.civcraft.mc.namelayer.GroupManager$1.run(GroupManager.java:98)
2015-05-28 12:18:37 [WARN]      at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
2015-05-28 12:18:37 [WARN]      at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
2015-05-28 12:18:37 [WARN]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-05-28 12:18:37 [WARN]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-05-28 12:18:37 [WARN]      at java.lang.Thread.run(Thread.java:745)

There was about 50 of these that triggered in a row.

**Comment by rourke750** [comment]
weird bug.  I have it if the player is on the group then remove them first and readd them.  Not sure why it didnt work this time.  Might be possible this group was messed up from citadel 2.0.  Was this the only time this has happened?

**Comment by erocs** [comment]
The player tried it twice today and both times lit the console up with a
ton of this exception spew, one for each player.

**Comment by rourke750** [comment]
Can you check and see if both groups exist.  If the player merged the group
then he shouldnt have been able to do it twice.

**Comment by ttk2** [comment]
staged for tomorrow.

**Comment by suirad** [comment]
Status of this?

**Comment by suirad** [comment]
Status of this? I think #128 is related as well

**Comment by ttk2** [comment]
seems resolved.

**Comment by erocs** [comment]
It may seem resolved, but really how often is /nlmg used?

**Comment by ttk2** [comment]
very true, think we shoudl reopen adn try to reproduce?
