### ISSUE TITLE
AssociationList.getUUID Closed ResultSet

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#109]
2015-05-28 13:27:05 [WARN] java.sql.SQLException: Operation not allowed after ResultSet closed
2015-05-28 13:27:05 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
2015-05-28 13:27:05 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
2015-05-28 13:27:05 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
2015-05-28 13:27:05 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
2015-05-28 13:27:05 [WARN]      at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
2015-05-28 13:27:05 [WARN]      at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:838)
2015-05-28 13:27:05 [WARN]      at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5656)
2015-05-28 13:27:05 [WARN]      at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5576)
2015-05-28 13:27:05 [WARN]      at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5616)
2015-05-28 13:27:05 [WARN]      at vg.civcraft.mc.namelayer.database.AssociationList.getUUID(AssociationList.java:105)
2015-05-28 13:27:05 [WARN]      at vg.civcraft.mc.namelayer.NameAPI.getUUID(NameAPI.java:24)
2015-05-28 13:27:05 [WARN]      at vg.civcraft.mc.civchat2.CivChat2Manager.sendGroupMsg(CivChat2Manager.java:436)
2015-05-28 13:27:05 [WARN]      at vg.civcraft.mc.civchat2.listeners.CivChat2Listener.PlayerChatEvent(CivChat2Listener.java:98)
2015-05-28 13:27:05 [WARN]      at sun.reflect.GeneratedMethodAccessor262.invoke(Unknown Source)
2015-05-28 13:27:05 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-05-28 13:27:05 [WARN]      at java.lang.reflect.Method.invoke(Method.java:497)
2015-05-28 13:27:05 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
2015-05-28 13:27:05 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2015-05-28 13:27:05 [WARN]      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
2015-05-28 13:27:05 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
2015-05-28 13:27:05 [WARN]      at net.minecraft.server.v1_8_R2.PlayerConnection.chat(PlayerConnection.java:1061)
2015-05-28 13:27:05 [WARN]      at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:999)
2015-05-28 13:27:05 [WARN]      at net.minecraft.server.v1_8_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
2015-05-28 13:27:05 [WARN]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2015-05-28 13:27:05 [WARN]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2015-05-28 13:27:05 [WARN]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-05-28 13:27:05 [WARN]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-05-28 13:27:05 [WARN]      at java.lang.Thread.run(Thread.java:745)
2015-05-28 13:27:05 [ERROR] Could not pass event AsyncPlayerChatEvent to CivChat2 v1.0.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.chat(PlayerConnection.java:1061) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:999) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.civchat2.CivChat2Manager.sendGroupMsg(CivChat2Manager.java:449) ~[?:?]
        at vg.civcraft.mc.civchat2.listeners.CivChat2Listener.PlayerChatEvent(CivChat2Listener.java:98) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor262.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 11 more

**Comment by rourke750** [comment]
What build of namelayer is up?

**Comment by erocs** [comment]
v2.3.5

**Comment by rourke750** [comment]
Of the jar i mean.

**Comment by erocs** [comment]
NameLayer-2.3.5-131.jar

Please increment the plugin's version instead of relying on build number...

**Comment by rourke750** [comment]
I need to figure out how to get jenkins to pull the version from maven and inject into the plugin.yml  136, fixes this.

**Comment by erocs** [comment]
I see a build 132 at http://civcraft.co:8080/job/NameLayer-master/

**Comment by rourke750** [comment]
Guh, can you forward civcraft.co:8080 to http://192.95.27.125:8080/ .  I thought ttk2 mentioned this to you?

**Comment by erocs** [comment]
We'll use build.civcraft.co from now on.

**Comment by erocs** [comment]
@ttk2 Does http://192.95.27.125:8080/job/NameLayer-master/136/ need testing? If not this should go online.

**Comment by ttk2** [comment]
I know know, that's rourkes determination.

**Comment by rourke750** [comment]
These are the only changes: https://github.com/Civcraft/NameLayer/commit/c357be874b2b765dc6e67394ce5133208df410dd#diff-ccd94b3aade3ad8210eac6c7d3584b15

The first part is to better handle tab completion, if that breaks its nothing too important and players will report.  The second part I just created preparedstatement objects inside the methods so no more of that resultset closed since they are all handling their own preparedstatement.  

I think its good to go but those words always seem to cause the worst kinds of problems.

Is this on civtest?  If its broken basicly logging in will show it.

**Comment by ttk2** [comment]
its on Civtest now, what should I look for?

**Comment by rourke750** [comment]
Log and if it doesnt crash youre good.  Pearl yourself, that triggers some
namelayer stuff.
