### ISSUE TITLE
"Can't load from MySQL" error

### ISSUE THREAD

**Issue by Murreey** [Civcraft/NameLayer#132]
Hi,

We're getting this error any time someone joins the game, apparently the plugin can't connect to the database. It still seems like it's managing to get the data correctly though, as people who've changed their names get the correct name loaded from the DB. New players login with "null joined the game". 

I've double checked the SQL connection info etc and it seems to be fine, and I can view the table in phpMyAdmin fine as well. Only recent change was updating our MySQL version to 5.5.45.

Running NameLayer v2.4.8 build #197, the latest.

Thanks!

Error:
```
[13:36:13] [Server thread/WARN]: java.sql.SQLException: Cannot load from mysql.proc. The table is probably corrupted
[13:36:13] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[13:36:13] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[13:36:13] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[13:36:13] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[13:36:13] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[13:36:13] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[13:36:13] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[13:36:13] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
[13:36:13] [Server thread/WARN]: 	at vg.civcraft.mc.namelayer.database.AssociationList.addPlayer(AssociationList.java:142)
[13:36:13] [Server thread/WARN]: 	at vg.civcraft.mc.namelayer.listeners.AssociationListener.OnPlayerJoin(AssociationListener.java:45)
[13:36:13] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor302.invoke(Unknown Source)
[13:36:13] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:36:13] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[13:36:13] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[13:36:13] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:36:13] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[13:36:13] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[13:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[13:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[13:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[13:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[13:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[13:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[13:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:813)
[13:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[13:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[13:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[13:36:13] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ttk2** [comment]
whats your config file look like?

**Comment by rourke750** [comment]
Doesnt look like anything from our end.  You might have corrupted your table while updating to a new mysql version.  

Try look at this http://www.myguysolutions.com/2013/10/30/how-to-resolve-mysql-error-code-1548-cannot-load-from-mysql-proc-the-table-is-probably-corrupted/

**Comment by erocs** [comment]
Definitely, try to manually insert a row to the table, outside of the plugin, and see what happens.

**Comment by Murreey** [comment]
Config file:
```
sql:
  hostname: {server address}
  port: 3306
  dbname: {db}
  username: {username}
  password: {password}
groups:
  enable: false
persistance:
  forceloadnamecaching: false
```

I tried manually inserting a row through phpMyAdmin and it worked fine, same with deleting it.

It's a hosted solution unfortunately so I don't have access to the server command line, I'm not sure if there's any way to 'repair' the table?

**Comment by erocs** [comment]
Does running "show procedure status;" list out your stored procedures fine? Is the addplayertotable procedure listed? Is there any error in the Minecraft log when NameLayer starts about being unable to create the addplayertotable procedure?

**Comment by Murreey** [comment]
Ah that looks like it - 'show procedure status' fails saying the table is corrupted, and there's an error on startup when it tries to create the procedure. I figure I'll have to contact the host and get them to fix whatever corrupted.

```
[06:57:00] [Server thread/ERROR]: [NameLayer] Could not execute SQL statement!
java.sql.SQLException: Cannot load from mysql.proc. The table is probably corrupted
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at vg.civcraft.mc.namelayer.database.Database.execute(Database.java:119) [NameLayer-2.4.8.jar:?]
	at vg.civcraft.mc.namelayer.database.AssociationList.initializeProcedures(AssociationList.java:59) [NameLayer-2.4.8.jar:?]
	at vg.civcraft.mc.namelayer.database.AssociationList.<init>(AssociationList.java:21) [NameLayer-2.4.8.jar:?]
	at vg.civcraft.mc.namelayer.NameLayerPlugin.loadDatabases(NameLayerPlugin.java:106) [NameLayer-2.4.8.jar:?]
	at vg.civcraft.mc.namelayer.NameLayerPlugin.onEnable(NameLayerPlugin.java:43) [NameLayer-2.4.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_55]
[06:57:00] [Server thread/ERROR]: [NameLayer] Could not execute SQL statement!
java.sql.SQLException: Cannot load from mysql.proc. The table is probably corrupted
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at vg.civcraft.mc.namelayer.database.Database.execute(Database.java:119) [NameLayer-2.4.8.jar:?]
	at vg.civcraft.mc.namelayer.database.AssociationList.initializeProcedures(AssociationList.java:60) [NameLayer-2.4.8.jar:?]
	at vg.civcraft.mc.namelayer.database.AssociationList.<init>(AssociationList.java:21) [NameLayer-2.4.8.jar:?]
	at vg.civcraft.mc.namelayer.NameLayerPlugin.loadDatabases(NameLayerPlugin.java:106) [NameLayer-2.4.8.jar:?]
	at vg.civcraft.mc.namelayer.NameLayerPlugin.onEnable(NameLayerPlugin.java:43) [NameLayer-2.4.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_55]
```

**Comment by Murreey** [comment]
Managed to repair the stored procedures, and it fixed the problem. Thanks very much!
