### ISSUE TITLE
Nllg error

### ISSUE THREAD

**Issue by rourke750** [Civcraft/NameLayer#152]
org.bukkit.command.CommandException: Unhandled exception executing command 'nllg' in plugin NameLayer v2.5.25
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.namelayer.command.commands.ListGroups.execute(ListGroups.java:78) ~[?:?]
        at vg.civcraft.mc.namelayer.command.CommandHandler.execute(CommandHandler.java:87) ~[?:?]
        at vg.civcraft.mc.namelayer.NameLayerPlugin.onCommand(NameLayerPlugin.java:69) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 15 more

**Comment by rourke750** [comment]
@erocs Did you fix this?

**Comment by erocs** [comment]
rourke750 Testing new format 3d61e2c  29 days ago

Doesn't look like it.

**Comment by Scuwr** [comment]
Is this still an issue?

**Comment by ProgrammerDan** [comment]
Likely: https://github.com/Civcraft/NameLayer/blame/master/NameLayerMain/src/vg/civcraft/mc/namelayer/command/commands/ListGroups.java#L84

Group is never checked to be null; this is a classic NPE source.

**Comment by Maxopoly** [comment]
Pretty sure this is no longer happening, so closing.
