### ISSUE TITLE
NPE when trying to get current name

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/NameLayer#167]
2016-02-14 18:58:27 [ERROR] Could not pass event PlayerChangeServerEvent to CivChat2 v1.2                                                                               [3/5019]│····························································
org.bukkit.event.EventException                                                                                                                                                 │····························································        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-880a532]                                                │····························································
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-880a532]                                                  │····························································
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-880a532]                                                │····························································        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-880a532]                                                │····························································
        at vg.civcraft.mc.bettershards.BetterShardsPlugin.teleportPlayerToServer(BetterShardsPlugin.java:161) [BetterShards-1.3.52.jar:?]                                       │····························································
        at vg.civcraft.mc.bettershards.BetterShardsAPI.connectPlayer(BetterShardsAPI.java:56) [BetterShards-1.3.52.jar:?]                                                       │····························································        at vg.civcraft.mc.bettershards.portal.portals.CuboidPortal.teleport(CuboidPortal.java:92) [BetterShards-1.3.52.jar:?]                                                   │····························································        at vg.civcraft.mc.bettershards.listeners.BetterShardsListener.playerMoveEvent(BetterShardsListener.java:163) [BetterShards-1.3.52.jar:?]                                │····························································
        at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source) ~[?:?]                                                                                                  │····························································
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]                                                         │····························································
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]                                                                                              │····························································
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-db6de12-880a532]                                                 │····························································        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-db6de12-880a532]                                                   │····························································
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-880a532]                                                │····························································
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-880a532]                                                │····························································        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [spigot.jar:git-Spigot-db6de12-880a532]                                                   │····························································
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-db6de12-880a532]                                                            │····························································
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.jar:git-Spigot-db6de12-880a532]                                    │····························································
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-880a532]                                                      │····························································
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]                                                                        │····························································
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]                                                                                       │····························································
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-880a532]                                                                    │····························································
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-880a532]                                                     │····························································        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-880a532]                                                     │····························································
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-880a532]                                                     │····························································
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-880a532]                                                   │····························································
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]                                                                                                          │····························································
Caused by: java.lang.NullPointerException                                                                                                                                       │····························································
        at vg.civcraft.mc.namelayer.database.AssociationList.getCurrentName(AssociationList.java:124) ~[?:?]                                                                    │····························································
        at vg.civcraft.mc.namelayer.NameAPI.getCurrentName(NameAPI.java:64) ~[?:?]                                                                                              │····························································
        at vg.civcraft.mc.civchat2.listeners.BetterShardsListener.PlayerChangeServer(BetterShardsListener.java:29) ~[?:?]                                                       │····························································        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]                                                                                   │····························································
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]                                                                 │····························································
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]                                                         │····························································
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]                                                                                              │····························································
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-880a532]                                                │····························································        ... 26 more

@rourke750 This happened when entering a portal, any idea why?

**Comment by rourke750** [comment]
Civchat error.  Make sure https://github.com/Civcraft/CivChat2/blob/master/src/vg/civcraft/mc/civchat2/listeners/BetterShardsListener.java#L29 is not null before passing.

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/CivChat2/commit/fb5b709fb09e9dc3701c4d7033e64d58b1fd0d89

**Comment by ttk2** [comment]
Should I update civchat on civtemp?

**Comment by Maxopoly** [comment]
I already did
