### ISSUE TITLE
MySQLIntegrityConstraintViolationException GroupManagerDao.setDefaultGroup

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#209]
[01:06:30] [Server thread/WARN]: [NameLayer] Problem setting user XYZ-UUID default group to XYZ
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'XYZ-UUID' for key 'PRIMARY'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at vg.civcraft.mc.namelayer.database.GroupManagerDao.setDefaultGroup(GroupManagerDao.java:1044) [NameLayer.jar:?]
        at vg.civcraft.mc.namelayer.group.DefaultGroupHandler.setDefaultGroup(DefaultGroupHandler.java:38) [NameLayer.jar:?]
        at vg.civcraft.mc.namelayer.group.Group.setDefaultGroup(Group.java:425) [NameLayer.jar:?]
        at vg.civcraft.mc.namelayer.listeners.PlayerListener.handleFirstJoin(PlayerListener.java:112) [NameLayer.jar:?]
        at vg.civcraft.mc.namelayer.listeners.PlayerListener.playerJoinEvent(PlayerListener.java:37) [NameLayer.jar:?]
        at sun.reflect.GeneratedMethodAccessor188.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PlayerList.onPlayerJoin(PlayerList.java:333) [spigot.jar:git-Spigot-6016ac7-6d3efa0]

**Comment by suirad** [comment]
Shouldn't be an issue, looks like this value was set at the time as another. Could be closed.

**Comment by Maxopoly** [comment]
I think this was caused by default newfriend group creation assuming they dont already have a default group in combination with player data being reset and more newfriend groups being created. I'll leave it up for now, because I want to make some more changes to that newfriend group mechanic anyway to prevent this and some other issues

**Comment by Maxopoly** [comment]
Fixed as part of the other changes in the async PR.
