### ISSUE TITLE
Namelayer stack trace

### ISSUE THREAD

**Issue by ttk2** [Civcraft/NameLayer#21]
2015-01-31 17:35:10 [WARN] java.sql.SQLException: Operation not allowed after ResultSet closed                                                                         [10/8392]
2015-01-31 17:35:10 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
2015-01-31 17:35:10 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
2015-01-31 17:35:10 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
2015-01-31 17:35:10 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
2015-01-31 17:35:10 [WARN]      at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
2015-01-31 17:35:10 [WARN]      at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:7145)
2015-01-31 17:35:10 [WARN]      at vg.civcraft.mc.namelayer.database.GroupManagerDao.getAllMembers(GroupManagerDao.java:462)
2015-01-31 17:35:10 [WARN]      at vg.civcraft.mc.namelayer.group.Group.<init>(Group.java:35)
2015-01-31 17:35:10 [WARN]      at vg.civcraft.mc.namelayer.group.groups.PrivateGroup.<init>(PrivateGroup.java:23)
2015-01-31 17:35:10 [WARN]      at vg.civcraft.mc.namelayer.database.GroupManagerDao.getGroup(GroupManagerDao.java:399)
2015-01-31 17:35:10 [WARN]      at vg.civcraft.mc.namelayer.GroupManager.getGroup(GroupManager.java:110)
2015-01-31 17:35:10 [WARN]      at com.untamedears.JukeAlert.group.GroupMediator.getGroupsByAccount(GroupMediator.java:29)
2015-01-31 17:35:10 [WARN]      at com.untamedears.JukeAlert.storage.JukeAlertLogger.getSnitchList(JukeAlertLogger.java:654)
2015-01-31 17:35:10 [WARN]      at com.untamedears.JukeAlert.tasks.GetSnitchListPlayerTask.run(GetSnitchListPlayerTask.java:28)
2015-01-31 17:35:10 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
2015-01-31 17:35:10 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
2015-01-31 17:35:10 [WARN]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2015-01-31 17:35:10 [WARN]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2015-01-31 17:35:10 [WARN]      at java.lang.Thread.run(Thread.java:745)
2015-01-31 17:35:11 [WARN] java.sql.SQLException: Operation not allowed after ResultSet closed
2015-01-31 17:35:11 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
2015-01-31 17:35:11 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
2015-01-31 17:35:11 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
2015-01-31 17:35:11 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
2015-01-31 17:35:11 [WARN]      at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
2015-01-31 17:35:11 [WARN]      at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:7145)
2015-01-31 17:35:11 [WARN]      at vg.civcraft.mc.namelayer.database.GroupManagerDao.getAllMembers(GroupManagerDao.java:462)
2015-01-31 17:35:11 [WARN]      at vg.civcraft.mc.namelayer.group.Group.<init>(Group.java:35)
2015-01-31 17:35:11 [WARN]      at vg.civcraft.mc.namelayer.group.groups.PrivateGroup.<init>(PrivateGroup.java:23)
2015-01-31 17:35:11 [WARN]      at vg.civcraft.mc.namelayer.database.GroupManagerDao.getGroup(GroupManagerDao.java:399)
2015-01-31 17:35:11 [WARN]      at vg.civcraft.mc.namelayer.GroupManager.getGroup(GroupManager.java:110)
2015-01-31 17:35:11 [WARN]      at com.untamedears.JukeAlert.group.GroupMediator.getGroupsByAccount(GroupMediator.java:29)
2015-01-31 17:35:11 [WARN]      at com.untamedears.JukeAlert.storage.JukeAlertLogger.getSnitchList(JukeAlertLogger.java:654)
2015-01-31 17:35:11 [WARN]      at com.untamedears.JukeAlert.tasks.GetSnitchListPlayerTask.run(GetSnitchListPlayerTask.java:28)
2015-01-31 17:35:11 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
2015-01-31 17:35:11 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
2015-01-31 17:35:11 [WARN]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2015-01-31 17:35:11 [WARN]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2015-01-31 17:35:11 [WARN]      at java.lang.Thread.run(Thread.java:745)

**Comment by rourke750** [comment]
Is this still occurring?

**Comment by ttk2** [comment]
not that I have seen
