### ISSUE TITLE
ArrayIndexOutOfBoundsException MergeGUI.showScreen

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#210]
This could be CivModCore.

[00:08:38] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CivMenu v1.4.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1850) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 49
        at org.bukkit.craftbukkit.v1_10_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:105) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.craftbukkit.v1_10_R1.inventory.CraftInventory.setItem(CraftInventory.java:88) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventory.setSlot(ClickableInventory.java:86) ~[?:?]
        at vg.civcraft.mc.namelayer.gui.MergeGUI.showScreen(MergeGUI.java:72) ~[?:?]
        at vg.civcraft.mc.namelayer.gui.AdminFunctionsGUI.showMergingMenu(AdminFunctionsGUI.java:130) ~[?:?]
        at vg.civcraft.mc.namelayer.gui.AdminFunctionsGUI.access$100(AdminFunctionsGUI.java:26) ~[?:?]
        at vg.civcraft.mc.namelayer.gui.AdminFunctionsGUI$2.clicked(AdminFunctionsGUI.java:64) ~[?:?]
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventory.itemClick(ClickableInventory.java:138) ~[?:?]
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventoryListener.inventoryClick(ClickableInventoryListener.java:28) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor220.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        ... 15 more

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Civcraft/NameLayer/commit/30c51048fda92d6bd916a80a1f061adecf7dfdb7
