### ISSUE TITLE
ArrayIndexOutOfBoundsException CreateGroup.execute

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#211]
[02:31:08] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nlcg' in plugin NameLayer v2.8.06
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1348) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1183) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
        at vg.civcraft.mc.namelayer.command.commands.CreateGroup.execute(CreateGroup.java:71) ~[?:?]
        at vg.civcraft.mc.namelayer.command.CommandHandler.execute(CommandHandler.java:97) ~[?:?]
        at vg.civcraft.mc.namelayer.NameLayerPlugin.onCommand(NameLayerPlugin.java:86) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]

**Comment by ProgrammerDan** [comment]
Steps to reproduce? Is this still an issue?

**Comment by Maxopoly** [comment]
No, the item with the index 2 isn't used at all anymore in that command.
