### ISSUE TITLE
Better handling of bad commands 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/NameLayer#22]
2015-01-31 17:41:54 [INFO] XXXXX issued server command: /nltaai
2015-01-31 17:41:54 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'nltaai' in plugin NameLayer v2.2.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
        at vg.civcraft.mc.namelayer.command.commands.ToggleAutoAcceptInvites.execute(ToggleAutoAcceptInvites.java:36) ~[?:?]
        at vg.civcraft.mc.namelayer.command.CommandHandler.execute(CommandHandler.java:73) ~[?:?]
        at vg.civcraft.mc.namelayer.NameLayerPlugin.onCommand(NameLayerPlugin.java:53) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 13 more

**Comment by jjj5311** [comment]
Any idea how to recreate? I cannot make this happen in my local test server
