### ISSUE TITLE
/nltaai internal error

### ISSUE THREAD

**Issue by drjawa** [Civcraft/NameLayer#29]
2015-01-31 19:34:26 [INFO] ServalClaw issued server command: /nltaai
2015-01-31 19:34:26 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'nltaai' in plugin NameLayer v2.2.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02
dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013) [spigot.jar:git-Spigot-1.7.9-R0.2-2
03-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec
9b]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
        at vg.civcraft.mc.namelayer.command.commands.ToggleAutoAcceptInvites.execute(ToggleAutoAcceptInvites.java:40) ~[?:?]
        at vg.civcraft.mc.namelayer.command.CommandHandler.execute(CommandHandler.java:73) ~[?:?]
        at vg.civcraft.mc.namelayer.NameLayerPlugin.onCommand(NameLayerPlugin.java:53) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 13 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02de
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec
9b]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
        at vg.civcraft.mc.namelayer.command.commands.ToggleAutoAcceptInvites.execute(ToggleAutoAcceptInvites.java:40) ~[?:?]
        at vg.civcraft.mc.namelayer.command.CommandHandler.execute(CommandHandler.java:73) ~[?:?]
        at vg.civcraft.mc.namelayer.NameLayerPlugin.onCommand(NameLayerPlugin.java:53) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 13 more
>2015-01-31 19:34:26,388 ERROR An exception occurred processing Appender LogSnoopHandler java.lang.NullPointerException
        at com.untamedears.MiscLog.LogSnoopHandler.append(LogSnoopHandler.java:66)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
        at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:609)
        at org.bukkit.craftbukkit.v1_7_R4.util.ForwardLogHandler.publish(ForwardLogHandler.java:33)
        at java.util.logging.Logger.log(Logger.java:616)
        at java.util.logging.Logger.doLog(Logger.java:641)
        at java.util.logging.Logger.log(Logger.java:730)
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1019)
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850)
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184)
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/commit/f129d49f4967d284ec80b0d614a862dd183fcf4d

**Comment by ttk2** [comment]
just got the same stack

2015-01-31 21:46:30 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command
'nltaai' in plugin NameLayer v2.2.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at
net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
        at
vg.civcraft.mc.namelayer.command.commands.ToggleAutoAcceptInvites.execute(ToggleAutoAcceptInvites.java:36)
~[?:?]
        at
vg.civcraft.mc.namelayer.command.CommandHandler.execute(CommandHandler.java:73)
~[?:?]
        at
vg.civcraft.mc.namelayer.NameLayerPlugin.onCommand(NameLayerPlugin.java:53)
~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 13 more

**Comment by rourke750** [comment]
fixed in newst jar

**Comment by ttk2** [comment]
then the fix is online
