### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry

### ISSUE THREAD

**Issue by ttk2** [Civcraft/NameLayer#31]
2015-01-31 21:30:06 [INFO] XXXXXXXX issued server command: /nlag XXXXXXX
2015-01-31 21:30:06 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '7219db25-2ada-4d47-97e5-d2188975cc6b-3525' for key 'uq_m
eber_faction'
2015-01-31 21:30:06 [WARN]      at sun.reflect.GeneratedConstructorAccessor218.newInstance(Unknown Source)
2015-01-31 21:30:06 [WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2015-01-31 21:30:06 [WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
2015-01-31 21:30:06 [WARN]      at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2015-01-31 21:30:06 [WARN]      at com.mysql.jdbc.Util.getInstance(Util.java:382)
2015-01-31 21:30:06 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
2015-01-31 21:30:06 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
2015-01-31 21:30:06 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2015-01-31 21:30:06 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2015-01-31 21:30:06 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2015-01-31 21:30:06 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2015-01-31 21:30:06 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2015-01-31 21:30:06 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
2015-01-31 21:30:06 [WARN]      at vg.civcraft.mc.namelayer.database.GroupManagerDao.addMember(GroupManagerDao.java:455)
2015-01-31 21:30:06 [WARN]      at vg.civcraft.mc.namelayer.group.groups.PrivateGroup.addMember(PrivateGroup.java:29)
2015-01-31 21:30:06 [WARN]      at vg.civcraft.mc.namelayer.command.commands.AcceptInvite.execute(AcceptInvite.java:55)
2015-01-31 21:30:06 [WARN]      at vg.civcraft.mc.namelayer.command.CommandHandler.execute(CommandHandler.java:73)
2015-01-31 21:30:06 [WARN]      at vg.civcraft.mc.namelayer.NameLayerPlugin.onCommand(NameLayerPlugin.java:53)
2015-01-31 21:30:06 [WARN]      at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2015-01-31 21:30:06 [WARN]      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
2015-01-31 21:30:06 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
2015-01-31 21:30:06 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013)
2015-01-31 21:30:06 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850)
2015-01-31 21:30:06 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
2015-01-31 21:30:06 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
2015-01-31 21:30:06 [WARN]      at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184)
2015-01-31 21:30:06 [WARN]      at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
2015-01-31 21:30:06 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
2015-01-31 21:30:06 [WARN]      at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
2015-01-31 21:30:06 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
2015-01-31 21:30:06 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
2015-01-31 21:30:06 [WARN]      at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by fwhiffahder** [comment]
blue_muffinboy added me as member on PlayPen and PlayPenBastion, and I can tell I'm on the groups using /nlgs, but doors on the group won't open for me. They open for him, and he's a moderator.

**Comment by ttk2** [comment]
Still getting it, not dead yet

2015-02-01 10:22:17 [INFO] someguy issued server command: /nlag somegroup
2015-02-01 10:22:17 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '5b1aec58-9d87-4f0a-ab0c-58e0eccf3229-1931' for key 'uq_m
eber_faction'
2015-02-01 10:22:17 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2015-02-01 10:22:17 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2015-02-01 10:22:17 [WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2015-02-01 10:22:17 [WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
2015-02-01 10:22:17 [WARN]      at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2015-02-01 10:22:17 [WARN]      at com.mysql.jdbc.Util.getInstance(Util.java:382)
2015-02-01 10:22:17 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
2015-02-01 10:22:17 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
2015-02-01 10:22:17 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2015-02-01 10:22:17 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2015-02-01 10:22:17 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2015-02-01 10:22:17 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2015-02-01 10:22:17 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2015-02-01 10:22:17 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
2015-02-01 10:22:17 [WARN]      at vg.civcraft.mc.namelayer.database.GroupManagerDao.addMember(GroupManagerDao.java:455)
2015-02-01 10:22:17 [WARN]      at vg.civcraft.mc.namelayer.group.groups.PrivateGroup.addMember(PrivateGroup.java:29)
2015-02-01 10:22:17 [WARN]      at vg.civcraft.mc.namelayer.command.commands.AcceptInvite.execute(AcceptInvite.java:55)
2015-02-01 10:22:17 [WARN]      at vg.civcraft.mc.namelayer.command.CommandHandler.execute(CommandHandler.java:73)
2015-02-01 10:22:17 [WARN]      at vg.civcraft.mc.namelayer.NameLayerPlugin.onCommand(NameLayerPlugin.java:53)
2015-02-01 10:22:17 [WARN]      at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2015-02-01 10:22:17 [WARN]      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
2015-02-01 10:22:17 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
2015-02-01 10:22:17 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013)
2015-02-01 10:22:17 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850)
2015-02-01 10:22:17 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
2015-02-01 10:22:17 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
2015-02-01 10:22:17 [WARN]      at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184)
2015-02-01 10:22:17 [WARN]      at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
2015-02-01 10:22:17 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
2015-02-01 10:22:17 [WARN]      at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
2015-02-01 10:22:17 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
2015-02-01 10:22:17 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
2015-02-01 10:22:17 [WARN]      at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by rourke750** [comment]
closing for now
