### ISSUE TITLE
GroupManagerDao.mergeGroup MysqlDataTruncation 

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#33]
2015-01-31 22:34:48 [INFO] rourke750 issued server command: /nlmg rourke rourke750
2015-01-31 22:34:48 [WARN] com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect integer value: 'rourke' for column 'group_id' at row 1
2015-01-31 22:34:48 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3591)
2015-01-31 22:34:48 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2015-01-31 22:34:48 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2015-01-31 22:34:48 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2015-01-31 22:34:48 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2015-01-31 22:34:48 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2015-01-31 22:34:48 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
2015-01-31 22:34:48 [WARN]      at vg.civcraft.mc.namelayer.database.GroupManagerDao.mergeGroup(GroupManagerDao.java:616)
2015-01-31 22:34:48 [WARN]      at vg.civcraft.mc.namelayer.GroupManager.mergeGroup(GroupManager.java:91)
2015-01-31 22:34:48 [WARN]      at vg.civcraft.mc.namelayer.command.commands.MergeGroups$1.run(MergeGroups.java:83)
2015-01-31 22:34:48 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
2015-01-31 22:34:48 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
2015-01-31 22:34:48 [WARN]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2015-01-31 22:34:48 [WARN]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2015-01-31 22:34:48 [WARN]      at java.lang.Thread.run(Thread.java:745)

**Comment by rourke750** [comment]
can you run select * from faction_id where group_name = 'rourke'

**Comment by ttk2** [comment]
I see someone did this in the terminal did you get it rourke?

**Comment by rourke750** [comment]
yea I know whats' wrong.

**Comment by ProgrammerDan** [comment]
So, this issue is closed, TTK linked it to me, but ... I still can't access the blocks that used to be reinforced to the group that this botched merge deleted. So, I've got a bunch of factories and other infrastructure that is completely unusable. Any suggestions on restoration path?

**Comment by rourke750** [comment]
Yes, good.  Message me on reddit /u/rourke750 with cords to factories, what group they should be on.  I'll try sort it out tonight.
