### ISSUE TITLE
NPE GroupPermission.loadPermsforGroup

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#38]
2015-02-01 15:07:41 [WARN] Caused by: java.lang.NullPointerException
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.namelayer.permission.GroupPermission.loadPermsforGroup(GroupPermission.java:24)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.namelayer.permission.GroupPermission.<init>(GroupPermission.java:20)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.namelayer.permission.PermissionHandler.getGroupPermission(PermissionHandler.java:18)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.namelayer.GroupManager.getPermissionforGroup(GroupManager.java:139)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.reinforcement.PlayerReinforcement.<init>(PlayerReinforcement.java:33)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.database.CitadelReinforcementData.getReinforcement(CitadelReinforcementData.java:271)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager$2.load(ReinforcementManager.java:37)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager$2.load(ReinforcementManager.java:35)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
2015-02-01 15:07:41 [WARN]      ... 25 more

**Comment by rourke750** [comment]
SAme to assume that these https://github.com/Civcraft/NameLayer/issues/39 are related
