### ISSUE TITLE
SQLException ResultSet closed GroupManagerDao.getGroup

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#39]
2015-02-01 15:07:41 [WARN] java.sql.SQLException: Operation not allowed after ResultSet closed
2015-02-01 15:07:41 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
2015-02-01 15:07:41 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
2015-02-01 15:07:41 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
2015-02-01 15:07:41 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
2015-02-01 15:07:41 [WARN]      at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
2015-02-01 15:07:41 [WARN]      at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:838)
2015-02-01 15:07:41 [WARN]      at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2672)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.namelayer.database.GroupManagerDao.getGroup(GroupManagerDao.java:400)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.namelayer.GroupManager.getGroup(GroupManager.java:112)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.database.CitadelReinforcementData.getReinforcement(CitadelReinforcementData.java:271)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager$2.load(ReinforcementManager.java:37)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager$2.load(ReinforcementManager.java:35)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.get(LocalCache.java:3934)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:82)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:99)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.listener.BlockListener.interact(BlockListener.java:397)
2015-02-01 15:07:41 [WARN]      at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
2015-02-01 15:07:41 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-02-01 15:07:41 [WARN]      at java.lang.reflect.Method.invoke(Method.java:606)
2015-02-01 15:07:41 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
2015-02-01 15:07:41 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2015-02-01 15:07:41 [WARN]      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
2015-02-01 15:07:41 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
2015-02-01 15:07:41 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:375)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:662)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(SourceFile:60)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(SourceFile:9)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by rourke750** [comment]
This makes sense right https://github.com/Civcraft/NameLayer/commit/f11c48a00cdaed01445506f5432df6018806b9ee?

**Comment by erocs** [comment]
If you're going that route you should add it to all methods which make db calls. You can't be using a rowset while the connection can be used concurrently anywhere else.

**Comment by rourke750** [comment]
Alright, so that is the right approach?

**Comment by erocs** [comment]
If all the methods on this are synchronized it would prevent multiple simultaneous calls against this DB connection.
