### ISSUE TITLE
Disable /gm command when groups are disabled

### ISSUE THREAD

**Issue by Martijnie** [Civcraft/NameLayer#7]
Would it be possible to have the /gm command disable when groups are disabled in the config? Currently a lot of servers already use the /gm command to set the gamemode of a player, but NameLayer interfers with that:

````
[21:44:46 INFO]: Martijnie issued server command: /gm s
[21:44:46 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gm' in plugin NameLayer v2.1.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.namelayer.NameLayerPlugin.onCommand(NameLayerPlugin.java:51) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        ... 14 more
````

**Comment by erocs** [comment]
It should also be renamed. CivCraft's other plugins use a 2 letter code for the plugin followed by the command name, so /nlgm.

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/commit/d61397002f426851453d534360e802920b9d6a5d
