### ISSUE TITLE
NPE when setting new player profile

### ISSUE THREAD

**Issue by Martijnie** [Civcraft/NameLayer#8]
Getting the following error whenever a new player joins the server:

````
[17:28:06 ERROR]: Could not pass event PlayerLoginEvent to NameLayer v2.1.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.PlayerList.attemptLogin(PlayerList.java:414) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:97) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.namelayer.misc.v1_8_R1.ProfileModifier.setPlayerProfle(ProfileModifier.java:25) ~[?:?]
        at vg.civcraft.mc.namelayer.listeners.AssociationListener.loginEvent(AssociationListener.java:41) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor259.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        ... 13 more

````

**Comment by rourke750** [comment]
Do you get this with preexisting players?

**Comment by Martijnie** [comment]
Nope, only with new players.

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/commit/ca21fb23c7edc9ba73f7924b21f5600f95a3fe87

Try this: http://192.99.169.83:8080/job/NameLayer-master/38/  If it doesn't work please tell me.  Thx for bringing up these bugs.

**Comment by Martijnie** [comment]
Still getting the error, this part has changed though:

````
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.namelayer.misc.v1_8_R1.ProfileModifier.setPlayerProfle(ProfileModifier.java:25) ~[?:?]
        at vg.civcraft.mc.namelayer.listeners.AssociationListener.loginEvent(AssociationListener.java:41) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        ... 13 more
````

Thanks for fixing the bugs by the way, much appreciated :+1:

**Comment by rourke750** [comment]
Let me get home to test this.  Unfortunately I won't be home for a bit, I'll do it as soon as I get the chance.

**Comment by graywolf336** [comment]
Commenting to say that I get this error as well, using build 38.

**Comment by graywolf336** [comment]
Here is my stacktrace:
```java
[00:07:39] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to NameLayer v2.1.9
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at net.minecraft.server.v1_8_R1.PlayerList.attemptLogin(PlayerList.java:445) [spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:97) [spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:837) [spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:320) [spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:675) [spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:578) [spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	at java.lang.Thread.run(Thread.java:744) [?:1.7.0_45]
Caused by: java.lang.NullPointerException
	at vg.civcraft.mc.namelayer.misc.v1_8_R1.ProfileModifier.setPlayerProfle(ProfileModifier.java:25) ~[?:?]
	at vg.civcraft.mc.namelayer.listeners.AssociationListener.loginEvent(AssociationListener.java:41) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_45]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-PaperSpigot-cf5eecc-81ab957]
	... 13 more
```

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/commit/cafdcf9c28bf334d4e7abf67a25ab848f934e19e

Tested and confirmed fixed.  http://192.99.169.83:8080/job/NameLayer-master/39/
