### ISSUE TITLE
NPE in NameAPI.getUUID during async task

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#91]
Caused by: java.lang.NullPointerException
at com.mysql.jdbc.ResultSetImpl.buildIndexMapping(ResultSetImpl.java:750)
at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1108)
at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5616)
at vg.civcraft.mc.namelayer.database.AssociationList.getUUID(AssociationList.java:105)
at vg.civcraft.mc.namelayer.NameAPI.getUUID(NameAPI.java:21)

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/commit/c94a6b86865f13d0d399cd344333bd7b40368131

**Comment by ttk2** [comment]
on civtest
