### ISSUE TITLE
/nllg ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by erocs** [Civcraft/NameLayer#94]
2015-04-05 02:35:41 [INFO] Erocs issued server command: /nllg
2015-04-05 02:35:41 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'nllg' in plugin NameLayer v2.3.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at vg.civcraft.mc.namelayer.command.commands.ListGroups.execute(ListGroups.java:30) ~[?:?]
        at vg.civcraft.mc.namelayer.command.CommandHandler.execute(CommandHandler.java:86) ~[?:?]
        at vg.civcraft.mc.namelayer.NameLayerPlugin.onCommand(NameLayerPlugin.java:59) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 13 more

**Comment by jjj5311** [comment]
Where you vanished when you did this?

**Comment by rourke750** [comment]
No.  Look at the first part of the command. If he is an admin it works
differently then if he is s normal player.

**Comment by rourke750** [comment]
https://github.com/Civcraft/NameLayer/commit/c357be874b2b765dc6e67394ce5133208df410dd
